In [ ]:
!pip install -q transformers accelerate peft bitsandbytes
!pip install -q llamafactory

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/5398/LLaMA-Factory

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/5398/LLaMA-Factory

In [ ]:
from llamafactory.chat import ChatModel

args = dict(
    model_name_or_path="Qwen/Qwen2.5-7B-Instruct",
    adapter_name_or_path="Qwen2.5_lora",
    template="qwen",
    finetuning_type="lora"
)

chat_model = ChatModel(args)

[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,018 >> loading file vocab.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/vocab.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,019 >> loading file merges.txt from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/merges.txt
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,019 >> loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/tokenizer.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,019 >> loading file added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,020 >> loading file special_tokens_map.json from cache at None
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,021 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/tokenizer_config.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,021 >> loading file chat_template.jinja from cache at None
[INFO|tokenization_utils_base.py:2364] 2026-04-26 20:01:53,369 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO|configuration_utils.py:765] 2026-04-26 20:01:53,677 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/config.json
[INFO|configuration_utils.py:839] 2026-04-26 20:01:53,679 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,795 >> loading file vocab.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/vocab.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,796 >> loading file merges.txt from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/merges.txt
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,796 >> loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/tokenizer.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,797 >> loading file added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,797 >> loading file special_tokens_map.json from cache at None
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,798 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/tokenizer_config.json
[INFO|tokenization_utils_base.py:2095] 2026-04-26 20:01:53,798 >> loading file chat_template.jinja from cache at None
[INFO|tokenization_utils_base.py:2364] 2026-04-26 20:01:54,147 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO|configuration_utils.py:765] 2026-04-26 20:01:54,288 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/config.json
[INFO|configuration_utils.py:839] 2026-04-26 20:01:54,289 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": false,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

[WARNING|logging.py:328] 2026-04-26 20:01:54,290 >> `torch_dtype` is deprecated! Use `dtype` instead!

[INFO|2026-04-26 20:01:54] llamafactory.model.model_utils.kv_cache:143 >> KV cache is enabled for faster generation.

[WARNING|logging.py:328] 2026-04-26 20:01:56,965 >> `torch_dtype` is deprecated! Use `dtype` instead!
[INFO|modeling_utils.py:1172] 2026-04-26 20:01:56,967 >> loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/model.safetensors.index.json
[INFO|modeling_utils.py:1243] 2026-04-26 20:01:56,968 >> Will use dtype=torch.bfloat16 as defined in model's config object
[INFO|modeling_utils.py:2341] 2026-04-26 20:01:56,969 >> Instantiating Qwen2ForCausalLM model under default dtype torch.bfloat16.
[INFO|configuration_utils.py:986] 2026-04-26 20:01:56,971 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645
}

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

[INFO|configuration_utils.py:941] 2026-04-26 20:02:02,240 >> loading configuration file generation_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28/generation_config.json
[INFO|configuration_utils.py:986] 2026-04-26 20:02:02,241 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

[INFO|dynamic_module_utils.py:423] 2026-04-26 20:02:02,287 >> Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-7B-Instruct.

[INFO|2026-04-26 20:02:02] llamafactory.model.model_utils.attention:143 >> Using torch SDPA for faster training and inference.

/usr/local/lib/python3.12/dist-packages/peft/config.py:165: UserWarning: Unexpected keyword arguments ['alora_invocation_tokens', 'arrow_config', 'ensure_weight_tying', 'peft_version'] for class LoraConfig, these are ignored. This probably means that you're loading a configuration file that was saved using a higher version of the library and additional parameters have been introduced since. It is highly recommended to upgrade the PEFT version before continuing (e.g. by running `pip install -U peft`).
  warnings.warn(

[INFO|2026-04-26 20:02:05] llamafactory.model.adapter:143 >> Merged 1 adapter(s).
[INFO|2026-04-26 20:02:05] llamafactory.model.adapter:143 >> Loaded adapter(s): Qwen2.5_lora
[INFO|2026-04-26 20:02:05] llamafactory.model.loader:143 >> all params: 7,615,616,512

In [ ]:
system_text = "You are a seasoned stock market analyst. Your task is to list the positive developments and potential concerns for companies based on relevant news and basic financials from the past weeks, then provide an analysis and prediction for the companies' stock price movement for the upcoming week. Your answer format should be as follows:\n\n[Positive Developments]:\n1. ...\n\n[Potential Concerns]:\n1. ...\n\n[Prediction & Analysis]\nPrediction: ...\nAnalysis: ...\n\n"
messages = [
    {"role": "user", "content": system_text + "\n" +"[Company Introduction]:\n\nAmerican Express Co is a leading entity in the Financial Services sector. Incorporated and publicly traded since 1977-05-18, the company has established its reputation as one of the key players in the market. As of today, American Express Co has a market capitalization of 168338.49 in USD, with 723.87 shares outstanding.\n\nAmerican Express Co operates primarily in the US, trading under the ticker AXP on the NEW YORK STOCK EXCHANGE, INC.. As a dominant force in the Financial Services space, the company continues to innovate and drive progress within the industry.\n\nFrom 2024-02-11 to 2024-02-18, AXP's stock price increased from 211.81 to 211.90. News during this period are listed below:\n\n[Headline]: American Express: Buy, Sell, or Hold?\n[Summary]: With shares at all-time highs, investors still won't struggle in finding reasons to be bullish.\n\n[Headline]: American Express Co. stock underperforms Monday when compared to competitors\n[Summary]: Shares of American Express Co. slipped 0.10% to $212.26 Monday, on what proved to be an all-around mixed trading session for the stock market, with the Dow...\n\n[Headline]: The Next Berkshire Hathaway? 3 Blue-Chip Stocks That Investors Shouldn’t Ignore.\n[Summary]: Blue chip stocks are what many investors look for when trying to add new stocks to their portfolios. What really are these companies? Well, a blue chip company is generally a well-known and well-established company that has a history of generating consistent profits. They have grown their revenue in the past and have worked to make a successful company. That’s why these are usually more reliable to invest in since they are not small startup companies that just hit the market and carry tons of ri\n\n[Headline]: Tracking Mario Gabelli's Gabelli Funds 13F Portfolio - Q4 2023 Update\n[Summary]: Gabelli Funds' 13F portfolio value increased by approximately 5% in Q4 2023. Click here to read more about Mario Gabelli's holdings and trades for Q4 2023.\n\n[Headline]: American Express Co. stock underperforms Thursday when compared to competitors despite daily gains\n[Summary]: Shares of American Express Co. inched 0.77% higher to $212.53 Thursday, on what proved to be an all-around positive trading session for the stock market,...\n\nFrom 2024-02-18 to 2024-02-25, AXP's stock price increased from 211.90 to 213.90. News during this period are listed below:\n\n[Headline]: The Dow is due for a change. These sectors may be affected.\n[Summary]: The keepers of the Dow Jones Industrial Average will have to make at least one change to the venerable index next week, and there’s a very good chance...\n\n[Headline]: Discover Stock Jumps on Capital One Deal News\n[Summary]: Shares of Discover Financial Services jumped in early trading following the news that Capital One will buy the credit-card company for more than $35 billion.  Discover's shares were up 14% in recent trading, while Capital One's rose 1%.  Capital One stock was up more than 4%.\n\n[Headline]: Got $1,000? 3 Payments Stocks to Buy and Hold Forever\n[Summary]: Americans spend trillions of dollars on debit and credit cards; these three companies are behind almost every transaction.\n\n[Headline]: Are You a Growth Investor? This 1 Stock Could Be the Perfect Pick\n[Summary]: The Zacks Style Scores offers investors a way to easily find top-rated stocks based on their investing style. Here's why you should take advantage.\n\n[Headline]: Nearly One-Fifth of Warren Buffett-Led Berkshire Hathaway's $368 Billion Stock Portfolio Is Invested in These 2 Financial Giants\n[Summary]: These two industry heavyweights should be on your investing radar.\n\nSome recent basic financials of AXP, reported at 2023-12-31, are presented below:\n\n[Basic Financials]:\n\nassetTurnoverTTM: 0.2635\nbookValue: 28057\ncashRatio: 0.31986958884260097\ncurrentRatio: 0.7395\nebitPerShare: 3.4553\neps: 2.6589\nev: 268910.19\nfcfMargin: 0.3691\nfcfPerShareTTM: 23.5076\ngrossMargin: 0.6334\nlongtermDebtTotalAsset: 0.1833\nlongtermDebtTotalCapital: 0.232\nlongtermDebtTotalEquity: 1.706\nnetDebtToTotalCapital: 0.6415\nnetDebtToTotalEquity: 4.7185\nnetMargin: 0.1125\noperatingMargin: 0.1462\npayoutRatioTTM: 0.2126\npb: 4.8659\npeTTM: 16.3032\npfcfTTM: 7.6988\npretaxMargin: 0.1462\npsTTM: 2.0881\nquickRatio: 0.7395\nreceivablesTurnoverTTM: 1.1117\nroaTTM: 0.0338\nroeTTM: 0.3099\nroicTTM: 0.0422\nrotcTTM: 0.053\nsalesPerShare: 23.6369\nsgaToSale: 0.3666\ntotalDebtToEquity: 6.355\ntotalDebtToTotalAsset: 0.6829\ntotalDebtToTotalCapital: 0.864\ntotalRatio: 1.1204\n\nBased on all the information before 2024-02-25, let's first analyze the positive developments and potential concerns for AXP. Come up with 2-4 most important factors respectively and keep them concise. Most factors should be inferred from company related news. Then make your prediction of the AXP cryptocurrency price movement for next week (2024-02-25 to 2024-03-03). Provide a summary analysis to support your prediction."}
]

response = ""
for new_text in chat_model.stream_chat(messages):
    print(new_text, end="", flush=True)
    response += new_text

[Positive Developments]:
1. American Express Co. has been consistently recognized as a blue-chip stock, a sign of its reliability and stability in the market.
2. American Express has been mentioned as a perfect pick for growth investors, indicating a positive outlook for its stock.
3. The company's financials show a good return on equity (roeTTM: 0.3099) and a decent free cash flow per share (fcfPerShareTTM: 23.5076), which are positive signs for the company's financial health.

[Potential Concerns]:
1. American Express Co. has underperformed compared to its competitors on certain trading days, which could be a concern for investors.
2. The company's total debt to equity ratio is quite high (totalDebtToEquity: 6.355), indicating that the company is heavily leveraged, which could pose a risk if interest rates rise or if the company's profits decline.
3. The company's current ratio (0.7395) is less than 1, indicating potential liquidity issues in the short term.

[Prediction & Analysis]:
Prediction: Down by 1-2%
Analysis: Despite the positive developments, the potential concerns seem to outweigh the positives in the short term. The company's high debt-to-equity ratio could be a concern for investors, especially if interest rates rise, which could increase the company's interest expenses. The underperformance compared to its competitors on certain trading days, along with the potential liquidity issues indicated by the current ratio, could also be a cause for concern. Therefore, the prediction for the next week is a downward movement of 1-2% in the company's stock price. However, it is important to note that the company's long-term prospects remain positive due to its recognition as a blue-chip stock and its healthy return on equity.

In [ ]:
system_text = """
You are a financial news signal extractor.

Your task is to extract structured signals from financial news for a specific company.

For each news item, output:

[News Signal]
- Event Type: (earnings / M&A / analyst / macro / competition / general)
- Sentiment: (-1 to 1, negative = bearish, positive = bullish for the company)
- Urgency: (0 to 1, how new or impactful the information is)
- Relevance: (0 to 1, how directly this news affects the company)
- Confidence: (0 to 1)

Rules:
- Focus ONLY on the target company
- Do NOT generate explanations
- Output one block per news item

OUTPUT FORMAT (STRICT JSON ONLY):
{
  "event_type": "earnings | M&A | analyst | macro | competition | general",
  "sentiment": float (-1 to 1),
  "urgency": float (0 to 1),
  "relevance": float (0 to 1),
  "confidence": float (0 to 1)
}

"""

In [ ]:
response = ""

messages = [
    {
        "role": "user",
        "content": system_text + "\n\n" + f"""
Target Company: American Express (AXP)

Headline: American Express: Buy, Sell, or Hold?
Summary: With shares at all-time highs, investors still won't struggle in finding reasons to be bullish.
"""
    }
]

for new_text in chat_model.stream_chat(messages):
    print(new_text, end="", flush=True)
    response += new_text

{
  "event_type": "general",
  "sentiment": 0.7,
  "urgency": 0.1,
  "relevance": 0.8,
  "confidence": 0.9
}

In [ ]:
import pandas as pd

In [ ]:
df_ini = pd.read_json("/content/drive/MyDrive/5398/LLaMA-Factory/data/df_test_system.json")

In [ ]:
df_ini.head()

,instruction,input,output,system
0,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...
1,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n\n1. The merger betw...,You are a seasoned stock market analyst. Your ...
2,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. The company recen...,You are a seasoned stock market analyst. Your ...
3,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Strong Dividend P...,You are a seasoned stock market analyst. Your ...
4,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Increasing Divide...,You are a seasoned stock market analyst. Your ...

In [ ]:
df_ini['instruction_copy'] = df_ini['instruction'].copy()

In [ ]:
df_ini.head()

,instruction,input,output,system,instruction_copy
0,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,[Company Introduction]:\n\nAmerican Express Co...
1,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n\n1. The merger betw...,You are a seasoned stock market analyst. Your ...,[Company Introduction]:\n\nAmerican Express Co...
2,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. The company recen...,You are a seasoned stock market analyst. Your ...,[Company Introduction]:\n\nAmerican Express Co...
3,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Strong Dividend P...,You are a seasoned stock market analyst. Your ...,[Company Introduction]:\n\nAmerican Express Co...
4,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Increasing Divide...,You are a seasoned stock market analyst. Your ...,[Company Introduction]:\n\nAmerican Express Co...

In [ ]:
marker = "News during this period are listed below"

df_ini['instruction_copy'] = (
    df_ini['instruction']
    .str.split(marker, n=1)
    .str[1]
)

In [ ]:
df_ini.head()

,instruction,input,output,system,instruction_copy
0,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ..."
1,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n\n1. The merger betw...,You are a seasoned stock market analyst. Your ...,:\n\n[Headline]: The Dow is due for a change. ...
2,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. The company recen...,You are a seasoned stock market analyst. Your ...,:\n\n[Headline]: American Express Co. stock un...
3,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Strong Dividend P...,You are a seasoned stock market analyst. Your ...,:\n\n[Headline]: March Dogs Of The Dow: Buy 1;...
4,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. Increasing Divide...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: James D. Robinson III, Who Tr..."

In [ ]:
import re

pattern = r"From\s+\d{4}-\d{2}-\d{2}\s+to\s+\d{4}-\d{2}-\d{2},.*?\[Headline\]"

df_ini['instruction_copy'] = df_ini['instruction_copy'].str.replace(
    pattern,
    "[Headline]",
    regex=True
)

In [ ]:
df_ini["instruction_copy"][0]

":\n\n[Headline]: American Express: Buy, Sell, or Hold?\n[Summary]: With shares at all-time highs, investors still won't struggle in finding reasons to be bullish.\n\n[Headline]: American Express Co. stock underperforms Monday when compared to competitors\n[Summary]: Shares of American Express Co. slipped 0.10% to $212.26 Monday, on what proved to be an all-around mixed trading session for the stock market, with the Dow...\n\n[Headline]: The Next Berkshire Hathaway? 3 Blue-Chip Stocks That Investors Shouldn’t Ignore.\n[Summary]: Blue chip stocks are what many investors look for when trying to add new stocks to their portfolios. What really are these companies? Well, a blue chip company is generally a well-known and well-established company that has a history of generating consistent profits. They have grown their revenue in the past and have worked to make a successful company. That’s why these are usually more reliable to invest in since they are not small startup companies that just hit the market and carry tons of ri\n\n[Headline]: Tracking Mario Gabelli's Gabelli Funds 13F Portfolio - Q4 2023 Update\n[Summary]: Gabelli Funds' 13F portfolio value increased by approximately 5% in Q4 2023. Click here to read more about Mario Gabelli's holdings and trades for Q4 2023.\n\n[Headline]: American Express Co. stock underperforms Thursday when compared to competitors despite daily gains\n[Summary]: Shares of American Express Co. inched 0.77% higher to $212.53 Thursday, on what proved to be an all-around positive trading session for the stock market,...\n\nFrom 2024-02-18 to 2024-02-25, AXP's stock price increased from 211.90 to 213.90. News during this period are listed below:\n\n[Headline]: The Dow is due for a change. These sectors may be affected.\n[Summary]: The keepers of the Dow Jones Industrial Average will have to make at least one change to the venerable index next week, and there’s a very good chance...\n\n[Headline]: Discover Stock Jumps on Capital One Deal News\n[Summary]: Shares of Discover Financial Services jumped in early trading following the news that Capital One will buy the credit-card company for more than $35 billion.  Discover's shares were up 14% in recent trading, while Capital One's rose 1%.  Capital One stock was up more than 4%.\n\n[Headline]: Got $1,000? 3 Payments Stocks to Buy and Hold Forever\n[Summary]: Americans spend trillions of dollars on debit and credit cards; these three companies are behind almost every transaction.\n\n[Headline]: Are You a Growth Investor? This 1 Stock Could Be the Perfect Pick\n[Summary]: The Zacks Style Scores offers investors a way to easily find top-rated stocks based on their investing style. Here's why you should take advantage.\n\n[Headline]: Nearly One-Fifth of Warren Buffett-Led Berkshire Hathaway's $368 Billion Stock Portfolio Is Invested in These 2 Financial Giants\n[Summary]: These two industry heavyweights should be on your investing radar.\n\nSome recent basic financials of AXP, reported at 2023-12-31, are presented below:\n\n[Basic Financials]:\n\nassetTurnoverTTM: 0.2635\nbookValue: 28057\ncashRatio: 0.31986958884260097\ncurrentRatio: 0.7395\nebitPerShare: 3.4553\neps: 2.6589\nev: 268910.19\nfcfMargin: 0.3691\nfcfPerShareTTM: 23.5076\ngrossMargin: 0.6334\nlongtermDebtTotalAsset: 0.1833\nlongtermDebtTotalCapital: 0.232\nlongtermDebtTotalEquity: 1.706\nnetDebtToTotalCapital: 0.6415\nnetDebtToTotalEquity: 4.7185\nnetMargin: 0.1125\noperatingMargin: 0.1462\npayoutRatioTTM: 0.2126\npb: 4.8659\npeTTM: 16.3032\npfcfTTM: 7.6988\npretaxMargin: 0.1462\npsTTM: 2.0881\nquickRatio: 0.7395\nreceivablesTurnoverTTM: 1.1117\nroaTTM: 0.0338\nroeTTM: 0.3099\nroicTTM: 0.0422\nrotcTTM: 0.053\nsalesPerShare: 23.6369\nsgaToSale: 0.3666\ntotalDebtToEquity: 6.355\ntotalDebtToTotalAsset: 0.6829\ntotalDebtToTotalCapital: 0.864\ntotalRatio: 1.1204\n\nBased on all the information before 2024-02-25, let's first analyze the positive developments and potential concerns for AXP. Come up with 2-4 most important factors respectively and keep them concise. Most factors should be inferred from company related news. Then make your prediction of the AXP cryptocurrency price movement for next week (2024-02-25 to 2024-03-03). Provide a summary analysis to support your prediction."

In [ ]:
marker = r"\[Basic Financials\]"

df_ini['instruction_copy'] = df_ini['instruction_copy'].str.split(marker).str[0]

In [ ]:
df_ini["instruction_copy"][0]

":\n\n[Headline]: American Express: Buy, Sell, or Hold?\n[Summary]: With shares at all-time highs, investors still won't struggle in finding reasons to be bullish.\n\n[Headline]: American Express Co. stock underperforms Monday when compared to competitors\n[Summary]: Shares of American Express Co. slipped 0.10% to $212.26 Monday, on what proved to be an all-around mixed trading session for the stock market, with the Dow...\n\n[Headline]: The Next Berkshire Hathaway? 3 Blue-Chip Stocks That Investors Shouldn’t Ignore.\n[Summary]: Blue chip stocks are what many investors look for when trying to add new stocks to their portfolios. What really are these companies? Well, a blue chip company is generally a well-known and well-established company that has a history of generating consistent profits. They have grown their revenue in the past and have worked to make a successful company. That’s why these are usually more reliable to invest in since they are not small startup companies that just hit the market and carry tons of ri\n\n[Headline]: Tracking Mario Gabelli's Gabelli Funds 13F Portfolio - Q4 2023 Update\n[Summary]: Gabelli Funds' 13F portfolio value increased by approximately 5% in Q4 2023. Click here to read more about Mario Gabelli's holdings and trades for Q4 2023.\n\n[Headline]: American Express Co. stock underperforms Thursday when compared to competitors despite daily gains\n[Summary]: Shares of American Express Co. inched 0.77% higher to $212.53 Thursday, on what proved to be an all-around positive trading session for the stock market,...\n\nFrom 2024-02-18 to 2024-02-25, AXP's stock price increased from 211.90 to 213.90. News during this period are listed below:\n\n[Headline]: The Dow is due for a change. These sectors may be affected.\n[Summary]: The keepers of the Dow Jones Industrial Average will have to make at least one change to the venerable index next week, and there’s a very good chance...\n\n[Headline]: Discover Stock Jumps on Capital One Deal News\n[Summary]: Shares of Discover Financial Services jumped in early trading following the news that Capital One will buy the credit-card company for more than $35 billion.  Discover's shares were up 14% in recent trading, while Capital One's rose 1%.  Capital One stock was up more than 4%.\n\n[Headline]: Got $1,000? 3 Payments Stocks to Buy and Hold Forever\n[Summary]: Americans spend trillions of dollars on debit and credit cards; these three companies are behind almost every transaction.\n\n[Headline]: Are You a Growth Investor? This 1 Stock Could Be the Perfect Pick\n[Summary]: The Zacks Style Scores offers investors a way to easily find top-rated stocks based on their investing style. Here's why you should take advantage.\n\n[Headline]: Nearly One-Fifth of Warren Buffett-Led Berkshire Hathaway's $368 Billion Stock Portfolio Is Invested in These 2 Financial Giants\n[Summary]: These two industry heavyweights should be on your investing radar.\n\nSome recent basic financials of AXP, reported at 2023-12-31, are presented below:\n\n"

In [ ]:
marker = "Some recent basic financials of"

def truncate_from_last_marker(x):
    if pd.isna(x):
        return x
    idx = x.rfind(marker)
    if idx == -1:
        return x
    return x[:idx]

df_ini['instruction_copy'] = df_ini['instruction_copy'].apply(truncate_from_last_marker)

In [ ]:
df_ini["instruction_copy"][0]

":\n\n[Headline]: American Express: Buy, Sell, or Hold?\n[Summary]: With shares at all-time highs, investors still won't struggle in finding reasons to be bullish.\n\n[Headline]: American Express Co. stock underperforms Monday when compared to competitors\n[Summary]: Shares of American Express Co. slipped 0.10% to $212.26 Monday, on what proved to be an all-around mixed trading session for the stock market, with the Dow...\n\n[Headline]: The Next Berkshire Hathaway? 3 Blue-Chip Stocks That Investors Shouldn’t Ignore.\n[Summary]: Blue chip stocks are what many investors look for when trying to add new stocks to their portfolios. What really are these companies? Well, a blue chip company is generally a well-known and well-established company that has a history of generating consistent profits. They have grown their revenue in the past and have worked to make a successful company. That’s why these are usually more reliable to invest in since they are not small startup companies that just hit the market and carry tons of ri\n\n[Headline]: Tracking Mario Gabelli's Gabelli Funds 13F Portfolio - Q4 2023 Update\n[Summary]: Gabelli Funds' 13F portfolio value increased by approximately 5% in Q4 2023. Click here to read more about Mario Gabelli's holdings and trades for Q4 2023.\n\n[Headline]: American Express Co. stock underperforms Thursday when compared to competitors despite daily gains\n[Summary]: Shares of American Express Co. inched 0.77% higher to $212.53 Thursday, on what proved to be an all-around positive trading session for the stock market,...\n\nFrom 2024-02-18 to 2024-02-25, AXP's stock price increased from 211.90 to 213.90. News during this period are listed below:\n\n[Headline]: The Dow is due for a change. These sectors may be affected.\n[Summary]: The keepers of the Dow Jones Industrial Average will have to make at least one change to the venerable index next week, and there’s a very good chance...\n\n[Headline]: Discover Stock Jumps on Capital One Deal News\n[Summary]: Shares of Discover Financial Services jumped in early trading following the news that Capital One will buy the credit-card company for more than $35 billion.  Discover's shares were up 14% in recent trading, while Capital One's rose 1%.  Capital One stock was up more than 4%.\n\n[Headline]: Got $1,000? 3 Payments Stocks to Buy and Hold Forever\n[Summary]: Americans spend trillions of dollars on debit and credit cards; these three companies are behind almost every transaction.\n\n[Headline]: Are You a Growth Investor? This 1 Stock Could Be the Perfect Pick\n[Summary]: The Zacks Style Scores offers investors a way to easily find top-rated stocks based on their investing style. Here's why you should take advantage.\n\n[Headline]: Nearly One-Fifth of Warren Buffett-Led Berkshire Hathaway's $368 Billion Stock Portfolio Is Invested in These 2 Financial Giants\n[Summary]: These two industry heavyweights should be on your investing radar.\n\n"

In [ ]:
import re
import pandas as pd

def extract_headline_blocks(text):
    if pd.isna(text):
        return []

    pattern = r"(\[Headline\].*?)(?=\[Headline\]|$)"
    return re.findall(pattern, text, flags=re.S)


df_ini['new'] = df_ini['instruction_copy'].apply(extract_headline_blocks)


df_ini['id'] = range(len(df_ini))

df_exploded = df_ini.explode('new').reset_index(drop=True)

In [ ]:
df_exploded["new"][1]

'[Headline]: American Express Co. stock underperforms Monday when compared to competitors\n[Summary]: Shares of American Express Co. slipped 0.10% to $212.26 Monday, on what proved to be an all-around mixed trading session for the stock market, with the Dow...\n\n'

In [ ]:
df_exploded.head()

,instruction,input,output,system,instruction_copy,new,id
0,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ...","[Headline]: American Express: Buy, Sell, or Ho...",0
1,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ...",[Headline]: American Express Co. stock underpe...,0
2,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ...",[Headline]: The Next Berkshire Hathaway? 3 Blu...,0
3,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ...",[Headline]: Tracking Mario Gabelli's Gabelli F...,0
4,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a seasoned stock market analyst. Your ...,":\n\n[Headline]: American Express: Buy, Sell, ...",[Headline]: American Express Co. stock underpe...,0

In [ ]:
marker = "News during this period are listed below:"

df_exploded["company_intro"] = df_exploded["instruction"].str.split(marker, n=1).str[0]

In [ ]:
df_exploded['company_intro'][0]

"[Company Introduction]:\n\nAmerican Express Co is a leading entity in the Financial Services sector. Incorporated and publicly traded since 1977-05-18, the company has established its reputation as one of the key players in the market. As of today, American Express Co has a market capitalization of 168338.49 in USD, with 723.87 shares outstanding.\n\nAmerican Express Co operates primarily in the US, trading under the ticker AXP on the NEW YORK STOCK EXCHANGE, INC.. As a dominant force in the Financial Services space, the company continues to innovate and drive progress within the industry.\n\nFrom 2024-02-11 to 2024-02-18, AXP's stock price increased from 211.81 to 211.90. "

In [ ]:
df_exploded["company_intro"] = df_exploded["company_intro"].str[:-82]

In [ ]:
df_exploded["company_intro"][0]

'[Company Introduction]:\n\nAmerican Express Co is a leading entity in the Financial Services sector. Incorporated and publicly traded since 1977-05-18, the company has established its reputation as one of the key players in the market. As of today, American Express Co has a market capitalization of 168338.49 in USD, with 723.87 shares outstanding.\n\nAmerican Express Co operates primarily in the US, trading under the ticker AXP on the NEW YORK STOCK EXCHANGE, INC.. As a dominant force in the Financial Services space, the company continues to innovate and drive progress within the industry.\n\n'

In [ ]:
df_exploded.columns

Index(['instruction', 'input', 'output', 'system', 'instruction_copy', 'new',
       'id', 'company_intro'],
      dtype='object')

In [ ]:
df_exploded['system'] = """You are a financial news signal extractor.

Your task is to extract structured signals from financial news for a specific company.

For each news item, output:

[News Signal]
- Event Type: (earnings / M&A / analyst / macro / competition / general)
- Sentiment: (-1 to 1, negative = bearish, positive = bullish for the company)
- Urgency: (0 to 1, how new or impactful the information is)
- Relevance: (0 to 1, how directly this news affects the company)
- Confidence: (0 to 1)

Rules:
- Focus ONLY on the target company
- Do NOT generate explanations
- Output one block per news item

OUTPUT FORMAT (STRICT JSON ONLY):
{
  "event_type": "earnings | M&A | analyst | macro | competition | general",
  "sentiment": float (-1 to 1),
  "urgency": float (0 to 1),
  "relevance": float (0 to 1),
  "confidence": float (0 to 1)
}"""

In [ ]:
df_exploded["new"] = "\n\nnews to analyze:\n\n" + df_exploded["new"].astype(str)

In [ ]:
df_exploded.head()

,instruction,input,output,system,instruction_copy,new,id,company_intro
0,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...
1,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...
2,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: The Next B...,0,[Company Introduction]:\n\nAmerican Express Co...
3,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: Tracking M...,0,[Company Introduction]:\n\nAmerican Express Co...
4,[Company Introduction]:\n\nAmerican Express Co...,,[Positive Developments]:\n1. American Express'...,You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...

In [ ]:
system_text + "\n\n" + df_exploded['company_intro'][0] + "\n\n" + df_exploded['new'][0]

'\nYou are a financial news signal extractor.\n\nYour task is to extract structured signals from financial news for a specific company.\n\nFor each news item, output:\n\n[News Signal]\n- Event Type: (earnings / M&A / analyst / macro / competition / general)\n- Sentiment: (-1 to 1, negative = bearish, positive = bullish for the company)\n- Urgency: (0 to 1, how new or impactful the information is)\n- Relevance: (0 to 1, how directly this news affects the company)\n- Confidence: (0 to 1)\n\nRules:\n- Focus ONLY on the target company\n- Do NOT generate explanations\n- Output one block per news item\n\nOUTPUT FORMAT (STRICT JSON ONLY):\n{\n  "event_type": "earnings | M&A | analyst | macro | competition | general",\n  "sentiment": float (-1 to 1),\n  "urgency": float (0 to 1),\n  "relevance": float (0 to 1),\n  "confidence": float (0 to 1)\n}\n\n\n\n[Company Introduction]:\n\nAmerican Express Co is a leading entity in the Financial Services sector. Incorporated and publicly traded since 1977-05-18, the company has established its reputation as one of the key players in the market. As of today, American Express Co has a market capitalization of 168338.49 in USD, with 723.87 shares outstanding.\n\nAmerican Express Co operates primarily in the US, trading under the ticker AXP on the NEW YORK STOCK EXCHANGE, INC.. As a dominant force in the Financial Services space, the company continues to innovate and drive progress within the industry.\n\n\n\n\n\nnews to analyze:\n\n[Headline]: American Express: Buy, Sell, or Hold?\n[Summary]: With shares at all-time highs, investors still won\'t struggle in finding reasons to be bullish.\n\n'

In [ ]:
def run_one_row(system_text, company_text, news_text):
    response = ""

    messages = [
        {
            "role": "user",
            "content": system_text + "\n\n" + company_text + "\n\n" +news_text
        }
    ]

    for new_text in chat_model.stream_chat(messages):
        response += new_text

    return response

In [ ]:
from tqdm import tqdm

tqdm.pandas()

df_exploded['output'] = df_exploded.progress_apply(
    lambda row: run_one_row(row['system'], row['company_intro'], row['new']),
    axis=1
)

100%|██████████| 2997/2997 [2:41:28<00:00,  3.23s/it]

In [ ]:
df_exploded.to_csv("/content/drive/MyDrive/5398/LLaMA-Factory/df_news_analyst_qwen_output.csv", index=False, encoding="utf-8")

In [ ]:
df_exploded.to_json(
    "df_exploded_output.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

In [ ]:
import json
import re
import pandas as pd
def extract_json(text):
    if pd.isna(text):
        return None

    text = str(text)

    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None

    json_str = match.group()

    try:
        return json.loads(json_str)
    except:
        return None

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/5398/LLaMA-Factory/df_news_analyst_qwen_output.csv")

In [ ]:
df.head()

,instruction,input,output,system,instruction_copy,new,id,company_intro
0,[Company Introduction]:\n\nAmerican Express Co...,NaN,"[News Signal]:\n{\n ""event_type"": ""general"",\...",You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...
1,[Company Introduction]:\n\nAmerican Express Co...,NaN,"[News Signal]:\n{\n ""event_type"": ""general"",\...",You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...
2,[Company Introduction]:\n\nAmerican Express Co...,NaN,"[News Signal]:\n{\n ""event_type"": ""general"",\...",You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: The Next B...,0,[Company Introduction]:\n\nAmerican Express Co...
3,[Company Introduction]:\n\nAmerican Express Co...,NaN,"[News Signal]:\n{\n ""event_type"": ""general"",\...",You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: Tracking M...,0,[Company Introduction]:\n\nAmerican Express Co...
4,[Company Introduction]:\n\nAmerican Express Co...,NaN,"[News Signal 1]\n{\n ""event_type"": ""general"",...",You are a financial news signal extractor.\n\n...,":\n\n[Headline]: American Express: Buy, Sell, ...",\n\nnews to analyze:\n\n[Headline]: American E...,0,[Company Introduction]:\n\nAmerican Express Co...

In [ ]:
df["parsed"] = df["output"].apply(extract_json)

df = df[df["parsed"].notnull()].copy()

In [ ]:
#result is not stable enough, a small precentage of data doesn't provide"urgency" result
df = df[df["parsed"].apply(lambda x: isinstance(x, dict) and "urgency" in x)].copy()

df["sentiment"] = df["parsed"].apply(lambda x: x["sentiment"])
df["urgency"] = df["parsed"].apply(lambda x: x["urgency"])
df["relevance"] = df["parsed"].apply(lambda x: x["relevance"])
df["confidence"] = df["parsed"].apply(lambda x: x["confidence"])
df["event_type"] = df["parsed"].apply(lambda x: x["event_type"])

In [ ]:
df["signal"] = (
    df["sentiment"] *
    df["urgency"] *
    df["relevance"] *
    df["confidence"]
)

In [ ]:
weekly_signal = df.groupby("id").apply(
    lambda x: (
        (x["sentiment"] * x["urgency"] * x["relevance"] * x["confidence"])
        .sum()
    )
)

/tmp/ipykernel_4203/770405051.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  weekly_signal = df.groupby("id").apply(

In [ ]:
weekly_signal = (weekly_signal - weekly_signal.mean()) / weekly_signal.std()

In [ ]:
weekly_signal.head()

id
0   -0.151223
1   -0.795613
2   -0.476289
3    0.343589
4    0.006619
dtype: float64

In [ ]:
def to_position(x):
    if x > 1:
        return 1
    elif x < -1:
        return -1
    else:
        return 0

positions = weekly_signal.apply(to_position)

In [ ]:
#weekly_signal.to_csv("/content/drive/MyDrive/5398/LLaMA-Factory/weekly_signal(dropNA).csv", index=True)

In [ ]:
#positions.to_csv("/content/drive/MyDrive/5398/LLaMA-Factory/trading_signal(dropNA).csv", index=True)